### ISSUE TITLE
 audio_lm and mulan_embed_quantizer are not defined

### ISSUE THREAD

**Issue by tralala87** [lucidrains/musiclm-pytorch#52]
audio_lm and mulan_embed_quantizer are not defined in the code provided on main page

**Comment by lucidrains** [comment]
should be clearer https://github.com/lucidrains/musiclm-pytorch/commit/80188c56a71daaac57589b4f022957838b2a03ac

**Comment by baardev** [comment]
> should be clearer [80188c5](https://github.com/lucidrains/musiclm-pytorch/commit/80188c56a71daaac57589b4f022957838b2a03ac)

Not sure how this makes anything clearer.  Did I miss something?  I installed `audiolm_pytorch`, via pip and via the GitHub code, and python sees the module, but where in the demo code is `audio_lm` defined?  The code comment says;
```
# you need the trained AudioLM (audio_lm) from above
# with the MulanEmbedQuantizer (mulan_embed_quantizer)
```
But nothing "above" returns a "trained AudioLM' object, nor any `audiolm_pytorch.audiolm_pytorch.AudioLM class`, and the `trainer()` itself returns nothing... so, where can I get the audio_lm object?

Would it be possible to adjust the demo code so that all one needs to do is supply the hubert files and sound files?
